os:
  - Visual Studio 2017
  - Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmake -H. -Bbuild -A%PLATFORM%

build:
  project: build\CLIntercept.sln
  parallel: true
  verbosity: normal
